CXX = g++
CXXFLAGS = -std=c++11 -I/opt/homebrew/opt/armadillo/include -I/opt/homebrew/opt/openblas/include -O3 -Wall
LDFLAGS = -L/opt/homebrew/opt/armadillo/lib -L/opt/homebrew/opt/openblas/lib -larmadillo -lopenblas

all: matmul_armadillo

matmul_armadillo: matmul_armadillo.o
	$(CXX) -o matmul_armadillo matmul_armadillo.o $(LDFLAGS)

matmul_armadillo.o: matmul_armadillo.cpp
	$(CXX) $(CXXFLAGS) -c matmul_armadillo.cpp

clean:
	rm -f matmul_armadillo.o matmul_armadillo
